### ISSUE TITLE
Debugging problem

### ISSUE THREAD

**Issue by omernsh** [AndreaCioccarelli/MusicDownloader#3]
apk is running smoothly, but when I debug version 1.1.1 source codes, I get an error, can you please help me as below?

`2018-11-13 10:53:27.754 26081-26081/com.andreacioccarelli.musicdownloader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.andreacioccarelli.musicdownloader, PID: 26081
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/KotlinPackage;
        at com.andreacioccarelli.musicdownloader.ui.drawables.GradientGenerator.getAppThemeGradient(GradientGenerator.kt:36)
        at com.andreacioccarelli.musicdownloader.ui.fragments.DownloadBottomDialog$processDownloadForReadyFile$1.run(DownloadBottomDialog.kt:323)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.KotlinPackage" on path: DexPathList[[zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/base.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_resources_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.andreacioccarelli.musicdownloader.ui.drawables.GradientGenerator.getAppThemeGradient(GradientGenerator.kt:36) 
        at com.andreacioccarelli.musicdownloader.ui.fragments.DownloadBottomDialog$processDownloadForReadyFile$1.run(DownloadBottomDialog.kt:323) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:172) 
        at android.app.ActivityThread.main(ActivityThread.java:6590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.andreacioccarelli.musicdownloader-62EjEWKBmpxVgLmmOXOBOA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:683)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:717)
        at android.app.LoadedApk.getResources(LoadedApk.java:944)
2018-11-13 10:53:27.755 26081-26081/com.andreacioccarelli.musicdownloader E/AndroidRuntime:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5675)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        		... 5 more
`

**Comment by cioccarellia** [comment]
For me it works fine. Let me some time to investigate

**Comment by omernsh** [comment]
Repostory also shared apk and release apk running but when I download and run the source code error occurs, thank you in advance.

**Comment by cioccarellia** [comment]
Check out the last 3 commits and the release v1.1.2. It should have fixed that.
